# Use the official Node.js image as the base
FROM node:latest

# Install AWS CLI and Terraform
RUN apt update && \
    apt install -y awscli unzip && \
    wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip && \
    unzip terraform_1.0.5_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_1.0.5_linux_amd64.zip && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app
