export const statesList = [
  { stateCode: "AC", stateDescription: "Acre (AC)" },
  { stateCode: "AL", stateDescription: "Alagoas (AL)" },
  { stateCode: "AP", stateDescription: "Amapá (AP)" },
  { stateCode: "AM", stateDescription: "Amazonas (AM)" },
  { stateCode: "BA", stateDescription: "Bahia (BA)" },
  { stateCode: "CE", stateDescription: "Ceará (CE)" },
  { stateCode: "DF", stateDescription: "Distrito Federal (DF)" },
  { stateCode: "ES", stateDescription: "Espírito Santo (ES)" },
  { stateCode: "GO", stateDescription: "Goiás (GO)" },
  { stateCode: "MA", stateDescription: "Maranhão (MA)" },
  { stateCode: "MT", stateDescription: "Mato Grosso (MT)" },
  { stateCode: "MS", stateDescription: "Mato Grosso do Sul (MS)" },
  { stateCode: "MG", stateDescription: "Minas Gerais (MG)" },
  { stateCode: "PA", stateDescription: "Pará (PA)" },
  { stateCode: "PB", stateDescription: "Paraíba (PB)" },
  { stateCode: "PR", stateDescription: "Paraná (PR)" },
  { stateCode: "PE", stateDescription: "Pernambuco (PE)" },
  { stateCode: "PI", stateDescription: "Piauí (PI)" },
  { stateCode: "RJ", stateDescription: "Rio de Janeiro (RJ)" },
  { stateCode: "RN", stateDescription: "Rio Grande do Norte (RN)" },
  { stateCode: "RS", stateDescription: "Rio Grande do Sul (RS)" },
  { stateCode: "RO", stateDescription: "Rondônia (RO)" },
  { stateCode: "RR", stateDescription: "Roraima (RR)" },
  { stateCode: "SC", stateDescription: "Santa Catarina (SC)" },
  { stateCode: "SP", stateDescription: "São Paulo (SP)" },
  { stateCode: "SE", stateDescription: "Sergipe (SE)" },
  { stateCode: "TO", stateDescription: "Tocantins (TO)" },
];
